### PR TITLE
Fix typo in flux_err check

### PR DESCRIPTION
**Pull request by Sniperq2**
Simple fix in if statement

### CODE REVIEW

**Comment by Sniperq2** [comment]
Why CI failed and how to fix it?

**Comment by barentsen** [comment]
@Sniperq2 Thank you for your contribution! We had unrelated errors in the tests at the time you opened this PR, which was not your fault.

The tests have now been fixed on the `main` branch.  Hence, the solution is to rebase this PR on the main branch. Would you be willing to do that?

**Comment by Sniperq2** [comment]
> @Sniperq2 Thank you for your contribution! We had unrelated errors in the tests at the time you opened this PR, which was not your fault.
> 
> The tests have now been fixed on the `main` branch. Hence, the solution is to rebase this PR on the main branch. Would you be willing to do that?
Yes, I think I could do this.

**Comment by Sniperq2** [comment]
That was hard. Did I do it right?

**Comment by barentsen** [comment]
This looks good.  All tests are passing now.  :+1:

Thank you for this valuable bug fix @Sniperq2!

**Pull request merged**
