### PR TITLE
Restore old `lc.bin()` functionality with new `aggregate_downsample`

### PR DESCRIPTION
**Pull request by dhomeier**
Follow-up of #995 to recreate the original `binsize` functionality of specifying a fixed number of points per bin (+ the sequence and string options for the special `astropy.stats.histogram` methods).
This **requires** the enhanced `aggregate_downsample` from astropy/astropy#11266. Could also address #1028; the behaviour of a scalar `bins` in the current version is unchanged from the existing one (or afaict from that in v1.11), i.e. a number `bins` of _equal-length_ bins; but it could be discussed if that should be changed to _equal-sample-size_, see comments in the function.
How to support all combinations of the `time_bin_start`, `time_bin_end`, `time_bin_size` with the existing parameters, and in what priority, probably also needs further discussion.
The tests have been updated to reflect results with and without the new astropy branch; I have disabled the check for `binned_lc.quality` entirely since there does not seem to be any mechanism implemented to bin this correctly (with bitwise `or`), and previously the test apparently just averaged by chance to the correct values.

### CODE REVIEW

**Comment by dhomeier** [comment]
1 failure now with 
```
>       assert underfit_metric_neighbors(lc_sap, min_targets=3, max_targets=3) < 0.9
E       assert 0.9259854773984688 < 0.9
E        +  where 0.9259854773984688 = underfit_metric_neighbors(<TessLightCurve length=18187 LABEL="TIC 388857263" SECTOR=11 AUTHOR=SPOC FLUX_ORIGIN=pdcsap_flux>\n       time         ...35  1.3812323e+05 ... -4.5290943e-03  1.6911790e-02\n1623.8955752075456  1.3825589e+05 ... -1.5050994e-03  2.1134768e-02, min_targets=3, max_targets=3)
```
not performing quite as poorly as it's supposed to; can't see an obvious connection to the changes in `bin()`.

**Comment by barentsen** [comment]
Good news: I believe the `underfit_metric_neighbors` failure is not related to this PR.  Instead, I believe it is caused by changes at the data archive (specifically, TESS data for certain sectors have been replaced with re-processed data).

**Comment by barentsen** [comment]
I fixed the failing test on the `main` branch via 81a370cabaa58534267e94a0bbfbf9f37feb7cd5, merged the changes into this PR branch, and started re-running the tests.  Fingers crossed!

**Comment by dhomeier** [comment]
Great, thanks!
I noted I had left some comments on further To-Do items like prioritising and testing different/conflicting bin kwargs; I had marked this ready for review since the basic functionality is there, but if you feel better test coverage for those cases is needed, leave a comment.

**Review by barentsen — APPROVED** [review]
Thanks again @dhomeier!  This looks like an excellent PR and a valuable fix. :+1:

 I intend to merge this in the next few hours, unless anybody objects?

**Pull request merged**
