### PR TITLE
compute_stats and get_transit_model added to API list

### PR DESCRIPTION
**Pull request by vvilhelmus**
Did this work?

### CODE REVIEW

**Comment by orionlee** [comment]
This looks good!

I just take a look the actual doc of the 2 methods. It'd be a bonus if we update the outdated reference to `astropy.stats.bls` (Astropy 3.x) with one referencing the updated class/method at:

https://docs.astropy.org/en/stable/api/astropy.timeseries.BoxLeastSquares.html

Syntax for referencing astropy classes/methods can be found in various other docstrings, e.g., the docstring of `from_lightcurve()` function.

**Comment by orionlee** [comment]
@vvilhelmus will this PR satisfy issue #1101 from your perspective?

**Comment by barentsen** [comment]
> At section 5 "pull upstream main" did not work for me

Oops, you are right, it should say `git pull upstream main` instead of `pull upstream main`.

**Comment by orionlee** [comment]
@vvilhelmus 
1. Would you be interested in fixing the outdated `astropy.stats.bls` references in the doc?
2. For issues in https://docs.lightkurve.org/about/contributing.html , you're welcome to open a PR to fix them, or file them in an issue so that we can keep track of it.

Thanks!

**Review by orionlee — APPROVED** [review]

**Comment by vvilhelmus** [comment]
Sam @orionlee , I have fixed the outdated BLS references, tested the new updated BLS references on my system, and managed to push the relevant periodogram.py file to this thread, yay! :raised_hands: 

When I was going to fix the contributing.rst file, I discovered that the missing 'git'-part had already been added by someone else, however, I cannot find any documentation about this recent fix yet, so I am not sure if I should push the change I did not fix myself to my fork on my Github account or do something else about it? :shrug:

**Review by orionlee — APPROVED** [review]

**Comment by orionlee** [comment]
@vvilhelmus Thanks! 

The updated BLS reference looks good.

For `contributing.rst` file, it looks like the missing `git` was indeed fixed in PR #1197 . So it does not need to be done twice:

https://github.com/lightkurve/lightkurve/blame/main/docs/source/about/contributing.rst#L145

The change was not pushed to docs.lightkurve.org yet, which generally gets updated when a new release is made. 
It should be mentioned in [CHANGES.rst](https://github.com/lightkurve/lightkurve/blob/main/CHANGES.rst), but it seems to have slipped through the crack. @barentsen or I would fix the `CHANGES.rst` when this PR is merged.

**Comment by vvilhelmus** [comment]
@orionlee & @barentsen  thank you for taking the time to teach me this. These fixes could more easily and much faster be done, when doing it yourselves. 
I didn't know about the CHANGES.rst file, I was actually browsing this forum looking for something that matches and after a while of finding nothing I just gave up.  :grin: 
Every time I post something here, I am learning something new, so again, thank you. :pray:

**Comment by orionlee** [comment]
@vvilhelmus 
1. In case there is confusion: `CHANGES.rst` is a convention used as a summary for user-facing changes (including documentation), e.g., test-only changes are usually not covered. For definitive actual changes, one should consult commit history / `git blame`, etc.
2. We'd like to include you in [AUTHORS.rst](https://github.com/lightkurve/lightkurve/blob/main/AUTHORS.rst). What'd be the name you prefer to be credited as?

**Pull request merged**
