### PR TITLE
Fix TPF interact select pixels problems with bokeh 2.3.x or later

### LINKED ISSUE #990: Couldn't select pixels of TPFs in interact()
**Problem description**
interact() is not working properly. I could not select the pixels in TPFs. When I try to select a pixel, the bottom row pixels automatically get selected. I could not select any pixel other than the bottom row pixels.

**Example**
```python
import lightkurve
tpf = lk.search_targetpixelfile("HL Tau", author='K2', campaign=13, cadence='long').download()
tpf.interact()
```

Screenshot (354)
Screenshot (356)

**Expected behavior**
When I click a pixel in the tpf stamp,  the pixel actually should get selected. But it doesn't. Instead, the pixels of the lowest row get selected. I couldn't select any pixel other than the pixels of the lowest row.

**Environment**
-  Windows
-  lightkurve version 2.0.3
-  installation method - pip
-  Executed the code in Python 3 in JupyterNotebook (version 6.2.0)

### PR DESCRIPTION
**Pull request by orionlee**
Close #990

The starting point is the stalled PR #1057.
If there are interests to get the issue resolved, I'd work on polishing it. Let me know.

Anecdotally, I came across a few people new to Lightkurve, could not get `tpf.interact()` to work because of this issue and gave it up. Resolving it would improve new user experience.

### CODE REVIEW

**Comment by orionlee** [comment]
@barentsen Ready for review. 

We should get this resolved soon. Applying the workaround (downgrade to bokeh 2.2.3) is getting more painful: https://github.com/lightkurve/lightkurve/issues/990#issuecomment-1088014846

Testing:
- some coverage in `test_interact.py`
- Manually tested with the bokeh v2.4.2 (latest) and v2.2.3 (the last version that worked with the released lightkurve 2.1.1) on Google Chrome Windows 11

**Comment by barentsen** [comment]
I manually tested this PR with bokeh v2.4.2 as well and was able to select pixels successfully again!

Screen Shot 2022-04-05 at 1 45 05 PM

**Comment by barentsen** [comment]
My only comment is that it looks like it is no longer possible to use "shift-clicking" to select multiple individual pixels.  I am referring to the behavior described in the second and third bullet in the [interact tutorial](https://docs.lightkurve.org/tutorials/1-getting-started/interactively-inspecting-data.html). 

Screen Shot 2022-04-05 at 1 48 56 PM

It doesn't look to me like the loss of "shift-clicking" is caused by this PR, so it may be another side effect of changes in bokeh?  Regardless, it is important to merge this PR to restore the basic functionality of interact, so it may be best to worry about "shift-clicking" in a separate issue.  Agreed?

**Comment by orionlee** [comment]
Shift-Clicking (add pixels) and Ctrl-Shift-Clicking (subtract pixels) both work in my testing (Windows, Google Chrome). 

It'd be great if we could find out why it didn't work for you: Shift-clicking not working would render the feature useless.

Could you test with in an environment using the released lightkurve 2.1.1 + older bokeh 2.2.3 (the last bokeh that would work without this PR)? [*] If shift-clicking does not work, then it could be something specific to your environment.

[*] Downgrading bokeh from the latest 2.4.2 to 2.2.3 could be a bit painful. See: https://github.com/lightkurve/lightkurve/issues/990#issuecomment-1088014846

**Comment by barentsen** [comment]
Interesting!  I tried both Firefox and Chrome on OSX.

...going to try with downgraded bokeh next.

**Comment by barentsen** [comment]
I've been trying to get bokeh 2.2.3 to work, but unfortunately I haven't been able to get past the `'output_notebook' is not defined` issue described in #990.

Regardless, I would be happy to go ahead, merge this PR, and release a new version, because this bugfix provides a vast improvement over the current situation with or without shift-click working on OSX!

**Comment by orionlee** [comment]
> Regardless, I would be happy to go ahead, merge this PR, and release a new version, because this bugfix provides a vast improvement over the current situation with or without shift-click working on OSX!

Assuming selecting single pixel still works for you, I'd also support merging the PR.

One idea to diagnose whether the shift-clicking issue you face is related to `Lightkurve`, or it is environment and/or bokeh issue.

---

- Are you using Jupyter notebook classic or Jupyter Lab? If it's Jupyter Lab, it's a known bokeh issue. 
- You can download this [notebook](https://gist.github.com/orionlee/5ec3d2498537206936d8cf821ad8ddf2) with a simple bokeh app. See if shift-clicking works.
  - It shift-clicking does not work, then the problem is probably related to the environment and/or bokeh.
  - it shift-clicking does work, , then probably something in `tpf.interact()` implementation that is causing the problem.

**Comment by barentsen** [comment]
> Assuming selecting single pixel still works for you

Yes, single pixel selection works fine.

> Are you using Jupyter notebook classic or Jupyter Lab?

Oops, I was using Jupyter Lab.  I tried Jupyter Notebook now and shift+click does work perfectly fine there! 🥳 

> You can download this [notebook](https://gist.github.com/orionlee/5ec3d2498537206936d8cf821ad8ddf2) with a simple bokeh app. See if shift-clicking works.

I confirmed that shift-clicking in this notebook works fine with Jupyter Notebook, and does *not* work with Jupyter Lab.

I think we can safely conclude that I encountered the bokeh bug you reported last year via https://github.com/bokeh/bokeh/issues/11324. Thanks so much for clearing this up.

We can merge this PR. Awesome work!!

**Comment by orionlee** [comment]
#1057 can also be closed. 

I wonder if gully faced the same issue as yours (using Bokeh on Jupyter Lab) last year, when he reported that something still didn't work in #1057. This PR is a refactored version of #1057, with no real behavior/logic change.

**Comment by barentsen** [comment]
Update: this fix has been included in the Lightkurve v2.2.0 release!

**Comment by gully** [comment]
YES!!!!! <3

**Pull request merged**
