### PR TITLE
Make Lightkurve compatible with Astropy v5.0 and Python 3.10

### PR DESCRIPTION
**Pull request by barentsen**
As reported by @dhomeier in https://github.com/lightkurve/lightkurve/issues/1161, a number of Lightkurve unit tests are currently failing with Astropy v5.0rc2.

I intend to use this PR to investigate and resolve those test failures.

### CODE REVIEW

**Comment by barentsen** [comment]
Note: a few outstanding issues affecting `LightCurve.bin()` are caused by edge case bugs in AstroPy's `aggregate_downsample` function.  I opened an AstroPy PR to resolve some of them: https://github.com/astropy/astropy/pull/12527

The implication is that we may want to support AstroPy v5.0.1 rather than v5.0.0.

**Comment by dhomeier** [comment]
I found another more serious bug with the new `MaskedQuantity`: this breaks `LombScarglePeriodogram` since `np.isnan(lc.flux)` is never triggered on flux with masked `NaN`s, returning `MaskedNDArray(False)` instead.
`lc.remove_nans()` itself works, but is not called because of this. `timeseries.LombScargle` however still returns all-NaN with the masked NaN inputs.
This is relatively easily caught, but I think `np.isnan` is such an ubiquitous test that it's probably worth another issue in Astropy; ideally I guess `timeseries.LombScargle` would just work with those inputs – I think that was the idea for the new `Masked` classes, but no idea how easily that might be realised.

**Comment by barentsen** [comment]
@dhomeier Interesting!  The issue you describe wasn't even on my radar yet.  Do you happen to have a minimum example that reproduces it?

**Comment by dhomeier** [comment]
Basically any lightcurve with NaNs in flux, I'd think – I ran into it trying to recreate the example from the [Periodogram Tutorial](https://docs.lightkurve.org/tutorials/3-science-examples/periodograms-creating-periodograms.html#2.-Creating-a-Periodogram-from-Kepler-Data)
```python
lc = lk.search_lightcurve('KIC 10264202', author="Kepler", quarter=10).download()
pg = lc.normalize(unit='ppm').to_periodogram()
np.isfinite(pg.power).any()
np.isnan(pg.power).all()
```

**Comment by barentsen** [comment]
Update: this PR is starting to near completion.  I made various small bugfixes to ensure the unit tests now pass with AstroPy v5.0.0 on Python 3.8, 3.9, and 3.10.  This ensures that Lightkurve can continue to be used with the latest versions of AstroPy and Python.

Note: this PR updates the minimum dependencies of Lightkurve to become python>=3.8 and astropy>=5.0.  These new requirements would take effect from the next release (v2.1).  Users of older versions of AstroPy and Python can of course continue to use Lightkurve v2.0.x, which we can maintain as needed.

One outstanding issue is the possible bug reported by @dhomeier above (https://github.com/lightkurve/lightkurve/pull/1162#issuecomment-983847177).  I expect to investigate this issue tomorrow.

**Comment by barentsen** [comment]
I was able to reproduce and fix the issue reported by @dhomeier above in https://github.com/lightkurve/lightkurve/pull/1162#issuecomment-983847177.  I also added a regression test.

I intend to merge this PR shortly and use it as the base for a Lightkurve v2.1 release soon.

I intend to make further modifications to the CI system by introducing the use of `tox`, but I will complete this work in a separate PR.

**Pull request merged**
