### PR TITLE
Fix lc.fill_gaps() and lc.query_solar_system_objects() with Astropy v5.0

### PR DESCRIPTION
**Pull request by keyuxing**
Unmasked values of `lc.flux_err` are required in `numpy.interp()`

### CODE REVIEW

**Comment by barentsen** [comment]
Thank you @keyuxing!

By chance, do you have a small example of a piece of code that fails because of this bug?  I'd like to add it as a unit test.

**Comment by keyuxing** [comment]
Yes. Here's the code:
```python
>>> import lightkurve as lk
>>> lc=lk.search_lightcurve('TIC24704868', sector=1, author='SPOC', exptime='short').download()
>>> lc.fill_gaps()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.9/site-packages/lightkurve/lightcurve.py", line 1183, in fill_gaps
    fe[~in_original] = np.interp(ntime[~in_original], lc.time.value, lc.flux_err)
  File "<__array_function__ internals>", line 5, in interp
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.9/site-packages/astropy/units/quantity.py", line 1705, in __array_function__
    result = super().__array_function__(function, types, args, kwargs)
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.9/site-packages/astropy/utils/masked/core.py", line 830, in __array_function__
    dispatched_result = dispatched_function(*args, **kwargs)
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.9/site-packages/astropy/utils/masked/function_helpers.py", line 795, in interp
    result = np.interp(xd, xp, fp, *args, **kwargs)
  File "<__array_function__ internals>", line 5, in interp
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.9/site-packages/numpy/lib/function_base.py", line 1439, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty
```

**Comment by keyuxing** [comment]
Hi! I added the unit test for `lc.fill_gaps()` and I'm looking forward to your review.

BTW, I just found another similar bug in `lc.query_solar_system_objects()` caused by the conflict with Astropy v5.0.
Here's the code:
```python
>>> import lightkurve as lk
>>> lc=lk.search_lightcurve('TIC9053429', sector=2, author='SPOC', exptime='short').download()
>>> lc.query_solar_system_objects(cadence_mask=(lc.time.value >= 1354.4) & (lc.time.value <= 1354.6))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.9/site-packages/lightkurve/lightcurve.py", line 1690, in query_solar_system_objects
    cadence_mask &= ~np.isnan(self.flux)
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.9/site-packages/astropy/utils/masked/core.py", line 674, in __array_ufunc__
    raise TypeError('cannot write to unmasked output')
TypeError: cannot write to unmasked output
```

**Comment by barentsen** [comment]
@keyuxing Thanks so much for this!  I plan to review and merge these changes shortly.

Note: I believe this issue is caused by a bug inside AstroPy.  I opened a bugfix here: https://github.com/astropy/astropy/pull/12978

**Comment by barentsen** [comment]
@keyuxing Thanks again for reporting this problem and contributing the fix! :+1: :+1:

I added a few comments to the code to document that the fix is a temporary workaround.  We should be able to remove the workaround once AstroPy is fixed via https://github.com/astropy/astropy/pull/12978

Note: unfortunately I had to remove the extra unit tests for `lc.query_solar_system_objects()` because they are very slow to run.

This is good to merge.  Thanks again! 🙏

**Pull request merged**
