### PR TITLE
Fix download error due to no dataURL in MAST result

### LINKED ISSUE #1377: Attempts to download from lightkurve results in a KeyError: 'dataURL'
#### Problem description
Hello.

When I try to download a target pixel file or a lightcurve from lightkurve, the download will not complete because of a KeyError. I am able to use cached files just fine. I used the same kind of code yesterday (October 30, 2023) and it worked just fine. There have been no updates to any packages that I am aware of in the interim--indeed, the first time I encountered this error I was in a virtual environment with an older version of lightkurve (and a few other packages).

#### Example

```python
import lightkurve as lk
lc3 = lk.search_lightcurve("TIC 179119903", sector=66).download()
```

#### Expected behavior
The download should complete.

If you would like the trace, it is here:
```python
lc3 = lk.search_lightcurve("TIC 179119903", sector=66).download()

~/anaconda3/lib/python3.8/site-packages/lightkurve/utils.py in wrapper(*args, **kwargs)
    561             sys.stdout = devnull
    562             try:
--> 563                 return f(*args, **kwargs)
    564             # restore to default
    565             finally:

~/anaconda3/lib/python3.8/site-packages/lightkurve/search.py in download(self, quality_bitmask, download_dir, cutout_size, **kwargs)
    421             )
    422 
--> 423         return self._download_one(
    424             table=self.table[:1],
    425             quality_bitmask=quality_bitmask,

~/anaconda3/lib/python3.8/site-packages/lightkurve/search.py in _download_one(self, table, quality_bitmask, download_dir, cutout_size, **kwargs)
    340             else:
    341                 from astroquery.mast import Observations
--> 342                 download_url = table[:1]["dataURL"][0]
    343                 log.debug("Started downloading {}.".format(download_url))
    344                 download_response = Observations.download_products(

~/anaconda3/lib/python3.8/site-packages/astropy/table/table.py in __getitem__(self, item)
   2073     def __getitem__(self, item):
   2074         if isinstance(item, str):
-> 2075             return self.columns[item]
   2076         elif isinstance(item, (int, np.integer)):
   2077             return self.Row(self, item)

~/anaconda3/lib/python3.8/site-packages/astropy/table/table.py in __getitem__(self, item)
    261         """
    262         if isinstance(item, str):
--> 263             return OrderedDict.__getitem__(self, item)
    264         elif isinstance(item, (int, np.integer)):
    265             return list(self.values())[item]

KeyError: 'dataURL'
```

I've played around a bit with the cache config to see if that had anything to do with it. It did not seem to.

#### Environment

-  platform (e.g. Linux, OSX, Windows): Linux (Ubuntu 20.04) and OSX
-  lightkurve version (e.g. 1.0b6): 2.4.0 (Ubuntu only) and 2.0.9 (both)
-  installation method (e.g. pip, conda, source): pip

### PR DESCRIPTION
**Pull request by orionlee**
Close #1377 

---
Changelog:

Fixed `SearchResult.download() / download_all()`'s misuse of dataURL. [#1380]

### CODE REVIEW

**Comment by orionlee** [comment]
A small, unrelated commit, 7693e28, was added to handle an unrelated changes in MAST search result for Kepler products, to handle the additional KBONUS-BKG product, which seems to be related to https://archive.stsci.edu/hlsp/kbonus-apexba 

I don't think anything needs to be changed on `lightkurve` side. But I am not familiar with Kepler products, so I call it out here just in case.

```python 
import lightkurve as lk
# insert code here ...

sr = lk.search_lightcurve("Kepler-10", mission="Kepler", cadence="long")
print(sr)
```
```
SearchResult containing 16 data products.

 #       mission      year   author   exptime         target_name          distance proposal_id
                                         s                                  arcsec             
--- ----------------- ---- ---------- ------- ---------------------------- -------- -----------
  0   Kepler Quarter  2009 KBONUS-BKG    1765 Gaia DR3 2132155017099178624      0.0         N/A
  1 Kepler Quarter 00 2009     Kepler    1800                kplr011904151      0.0          EX
  2 Kepler Quarter 01 2009     Kepler    1800                kplr011904151      0.0          EX
...
15 Kepler Quarter 17 2013     Kepler    1800                kplr011904151      0.0          EX
```

**Comment by scfleming** [comment]
Just a quick note, that is a new HLSP we just announced today (shortly, I'm working on the MAST announcement as we speak.)

**Comment by christinahedges** [comment]
@orionlee thanks for opening this PR, we're all just coming up against this new change now. I've updated two things on your PR, I've added the URL for this HLSP which @scfleming provided, and I've changed the ordering to make sure that this HLSP is not the first product that comes up (the mission product should be first in the list.)

@jorgemarpa and I will open a new PR to make sure there's a specific reader for this new HLSP. 

@orionlee I'm going to release a new version ASAP to make sure people can pip upgrade to get around this issue. Let's prepare for lots of new issues to open about this...!

**Comment by orionlee** [comment]
@christinahedges 

1. The [CHANGES.rst](https://github.com/lightkurve/lightkurve/blob/main/CHANGES.rst) in `main` is out of sync with the [v2.4.x](https://github.com/lightkurve/lightkurve/blob/v2.4.x/CHANGES.rst) version, essentially part of the issue #1378 [*]. It probably needs to be addressed before release.

2. For KBONUS-BKG support, I did a quick look yesterday, and suspect the following might need to be considered:
- each lightcurve file contains data stitched across multiple quarters. It could be surprising to users when they search for data in specific quarter, the KBONUS-BKG lightcurve will have results across multiple quarters.


---

[*] The current `main` CHANGES.rst is out of sync with the released 2.4.1 . It should be something like: 

```rst
2.4.2dev (unreleased)
=====================

- Updated plot style to default to higher resolution [#1311]
- Fixed download issue due to MAST API change [#1380]

2.4.1 (2023-09-06)
==================

- Updated interact features to work with JupyterHub (e.g. TiKE) [#1349]
- Exposed niters parameter in the PCA function of design matrix
- Fixed the aperture parsing functions inside TPFs to be compliant with `numpy` v1.25 [#1360]
```

**Comment by christinahedges** [comment]
@orionlee great catch, I lost track of this with all the MAST changes, I'll remedy it.

For the new HLSP, @jorgemarpa and I are the authors of the release so I'm working on putting in a fix now.

**Pull request merged**
