### PR TITLE
Implicit JupyterHub support

### PR DESCRIPTION
**Pull request by jaytmiller**
Modify show/interact functions to automatically supply a callable for the notebook_url parameter to adapt to operating behind the a JupyterHub proxy with randomly generated ports for the Bokeh server.   

This implements Bokeh's proposed fix here: https://docs.bokeh.org/en/latest/docs/user_guide/output/jupyter.html

An issue with more information / discussion is here:  https://github.com/lightkurve/lightkurve/issues/1348

While it may be premature (pending discussion),  this PR gives a concrete representation of what we're proposing.

### CODE REVIEW

**Comment by gully** [comment]
Hooray! I am glad to see a proposed fix here.  I had puzzled over this years ago.  Thanks @jaytmiller !

**Comment by christinahedges** [comment]
@jaytmiller thank you for opening a great PR! This fixes great functionality I'm really pleased to see it. I have just updated the tests to pass, and I've fixed a warning that occurs due to the astropy.time module. @Nschanche found the fix for the warnings, excellent work!

@Nschanche if the tests pass please can you give this a review and then if you're happy I'll merge!

**Comment by christinahedges** [comment]
Before we merge, can @Nschanche and @rebekah9969  look into making the `LK_JUPYTERHUB_EXTERNAL_URL` parameter part of the `config` in our `__init__` file, instead of an environment variable? 🙏

**Comment by christinahedges** [comment]
This functionality has now been merged in! Thank you for your PR, let me know if there's any issues as you use it.

**Pull request closed without merging**
